global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sentinel-fraud-platform'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sentinel-fraud-api'
    static_configs:
      - targets: ['fraud-api:8000']
    metrics_path: '/metrics-prometheus'
    scrape_interval: 5s

  - job_name: 'redpanda'
    static_configs:
      - targets: ['redpanda:9644']
    metrics_path: '/metrics'

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    bearer_token: ''
